ERROR - 2023-07-18 02:18:46 --> mysqli_sql_exception: Table 'pro-manger.users' doesn't exist in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT *\nFROM `...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(247): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(624): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Login.php(24): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Login->auth()
#8 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Login))
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-07-18 02:59:31 --> Class "App\Controllers\Deskapp\UserModel" not found
#0 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Login->auth()
#1 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Login))
#2 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2023-07-18 02:59:46 --> Class "App\Controllers\Deskapp\UserModel" not found
#0 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Login->auth()
#1 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Login))
#2 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2023-07-18 03:36:28 --> Class "App\Controllers\Deskapp\UserModel" not found
#0 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Login->auth()
#1 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Login))
#2 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
CRITICAL - 2023-07-18 03:59:34 --> Class "App\Controllers\Deskapp\UserModel" not found
#0 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Login->auth()
#1 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Login))
#2 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
ERROR - 2023-07-18 05:12:08 --> mysqli_sql_exception: Table 'pro-manger.users' doesn't exist in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT 1\nFROM `...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\MS\system\Validation\Rules.php(212): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\MS\system\Validation\Validation.php(305): CodeIgniter\Validation\Rules->is_unique('sm12@hotmail.co...', 'email', Array, NULL)
#6 C:\xampp\htdocs\MS\system\Validation\Validation.php(164): CodeIgniter\Validation\Validation->processRules('Email', 'Email', 'sm12@hotmail.co...', Array, Array)
#7 C:\xampp\htdocs\MS\system\Controller.php(181): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(34): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 05:12:39 --> mysqli_sql_exception: Table 'pro-manger.users' doesn't exist in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT 1\nFROM `...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\MS\system\Validation\Rules.php(212): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\MS\system\Validation\Validation.php(305): CodeIgniter\Validation\Rules->is_unique('sm12@hotmail.co...', 'email', Array, NULL)
#6 C:\xampp\htdocs\MS\system\Validation\Validation.php(164): CodeIgniter\Validation\Validation->processRules('Email', 'Email', 'sm12@hotmail.co...', Array, Array)
#7 C:\xampp\htdocs\MS\system\Controller.php(181): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(34): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 05:13:33 --> mysqli_sql_exception: Table 'pro-manger.users' doesn't exist in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT 1\nFROM `...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\MS\system\Validation\Rules.php(212): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\MS\system\Validation\Validation.php(305): CodeIgniter\Validation\Rules->is_unique('sm12@hotmail.co...', 'email', Array, NULL)
#6 C:\xampp\htdocs\MS\system\Validation\Validation.php(164): CodeIgniter\Validation\Validation->processRules('Email', 'Email', 'sm12@hotmail.co...', Array, Array)
#7 C:\xampp\htdocs\MS\system\Controller.php(181): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(34): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 05:14:00 --> mysqli_sql_exception: Table 'pro-manger.users' doesn't exist in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT 1\nFROM `...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\MS\system\Validation\Rules.php(212): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\MS\system\Validation\Validation.php(305): CodeIgniter\Validation\Rules->is_unique('sm12@hotmail.co...', 'email', Array, NULL)
#6 C:\xampp\htdocs\MS\system\Validation\Validation.php(164): CodeIgniter\Validation\Validation->processRules('Email', 'Email', 'sm12@hotmail.co...', Array, Array)
#7 C:\xampp\htdocs\MS\system\Controller.php(181): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(34): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 05:14:57 --> mysqli_sql_exception: Table 'pro-manger.users' doesn't exist in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT 1\nFROM `...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\MS\system\Validation\Rules.php(212): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\MS\system\Validation\Validation.php(305): CodeIgniter\Validation\Rules->is_unique('sm12@hotmail.co...', 'email', Array, NULL)
#6 C:\xampp\htdocs\MS\system\Validation\Validation.php(164): CodeIgniter\Validation\Validation->processRules('Email', 'Email', 'sm12@hotmail.co...', Array, Array)
#7 C:\xampp\htdocs\MS\system\Controller.php(181): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(34): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 05:15:42 --> mysqli_sql_exception: Table 'pro-manger.users' doesn't exist in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT 1\nFROM `...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\MS\system\Validation\Rules.php(212): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\MS\system\Validation\Validation.php(305): CodeIgniter\Validation\Rules->is_unique('sm12@hotmail.co...', 'email', Array, NULL)
#6 C:\xampp\htdocs\MS\system\Validation\Validation.php(164): CodeIgniter\Validation\Validation->processRules('Email', 'Email', 'sm12@hotmail.co...', Array, Array)
#7 C:\xampp\htdocs\MS\system\Controller.php(181): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(34): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-07-18 05:15:42 -->  is not a valid rule.
#0 C:\xampp\htdocs\MS\system\Validation\Validation.php(313): CodeIgniter\Validation\Exceptions\ValidationException::forRuleNotFound('')
#1 C:\xampp\htdocs\MS\system\Validation\Validation.php(164): CodeIgniter\Validation\Validation->processRules('Rules', 'Rules', NULL, Array, Array)
#2 C:\xampp\htdocs\MS\system\Controller.php(181): CodeIgniter\Validation\Validation->run()
#3 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(34): CodeIgniter\Controller->validate(Array)
#4 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#5 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#6 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2023-07-18 05:16:07 --> mysqli_sql_exception: Table 'pro-manger.users' doesn't exist in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT 1\nFROM `...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\MS\system\Validation\Rules.php(212): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\MS\system\Validation\Validation.php(305): CodeIgniter\Validation\Rules->is_unique('sm12@hotmail.co...', 'email', Array, NULL)
#6 C:\xampp\htdocs\MS\system\Validation\Validation.php(164): CodeIgniter\Validation\Validation->processRules('Email', 'Email', 'sm12@hotmail.co...', Array, Array)
#7 C:\xampp\htdocs\MS\system\Controller.php(181): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(34): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 05:16:52 --> mysqli_sql_exception: Table 'pro-manger.users' doesn't exist in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT 1\nFROM `...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\MS\system\Validation\Rules.php(212): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\MS\system\Validation\Validation.php(305): CodeIgniter\Validation\Rules->is_unique('sm12@hotmail.co...', 'email', Array, NULL)
#6 C:\xampp\htdocs\MS\system\Validation\Validation.php(164): CodeIgniter\Validation\Validation->processRules('Email', 'Email', 'sm12@hotmail.co...', Array, Array)
#7 C:\xampp\htdocs\MS\system\Controller.php(181): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(34): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-07-18 05:16:53 --> Attempt to read property "resultID" on bool
#0 C:\xampp\htdocs\MS\system\Model.php(281): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read...', 'C:\\xampp\\htdocs...', 281)
#1 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#2 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#3 C:\xampp\htdocs\MS\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#4 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(48): CodeIgniter\BaseModel->save(Array)
#5 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#6 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#7 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2023-07-18 05:19:57 --> mysqli_sql_exception: Table 'pro-manger.users' doesn't exist in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT 1\nFROM `...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\MS\system\Validation\Rules.php(212): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\MS\system\Validation\Validation.php(305): CodeIgniter\Validation\Rules->is_unique('sm12@hotmail.co...', 'email', Array, NULL)
#6 C:\xampp\htdocs\MS\system\Validation\Validation.php(164): CodeIgniter\Validation\Validation->processRules('Email', 'Email', 'sm12@hotmail.co...', Array, Array)
#7 C:\xampp\htdocs\MS\system\Controller.php(181): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(34): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-07-18 05:19:57 --> Attempt to read property "resultID" on bool
#0 C:\xampp\htdocs\MS\system\Model.php(281): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read...', 'C:\\xampp\\htdocs...', 281)
#1 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#2 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#3 C:\xampp\htdocs\MS\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#4 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(48): CodeIgniter\BaseModel->save(Array)
#5 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#6 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#7 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2023-07-18 06:06:06 --> mysqli_sql_exception: Table 'pro-manger.users' doesn't exist in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT 1\nFROM `...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\MS\system\Validation\Rules.php(212): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\MS\system\Validation\Validation.php(305): CodeIgniter\Validation\Rules->is_unique('sm12@hotmail.co...', 'email', Array, NULL)
#6 C:\xampp\htdocs\MS\system\Validation\Validation.php(164): CodeIgniter\Validation\Validation->processRules('Email', 'Email', 'sm12@hotmail.co...', Array, Array)
#7 C:\xampp\htdocs\MS\system\Controller.php(181): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(30): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-07-18 06:06:06 --> Attempt to read property "resultID" on bool
#0 C:\xampp\htdocs\MS\system\Model.php(281): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read...', 'C:\\xampp\\htdocs...', 281)
#1 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#2 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#3 C:\xampp\htdocs\MS\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#4 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(43): CodeIgniter\BaseModel->save(Array)
#5 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#6 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#7 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2023-07-18 06:14:41 --> mysqli_sql_exception: Table 'pro-manger.users' doesn't exist in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT 1\nFROM `...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\MS\system\Validation\Rules.php(212): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\MS\system\Validation\Validation.php(305): CodeIgniter\Validation\Rules->is_unique('sm12@hotmail.co...', 'email', Array, NULL)
#6 C:\xampp\htdocs\MS\system\Validation\Validation.php(164): CodeIgniter\Validation\Validation->processRules('Email', 'Email', 'sm12@hotmail.co...', Array, Array)
#7 C:\xampp\htdocs\MS\system\Controller.php(181): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(30): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-07-18 06:14:41 --> Class "App\Controllers\Deskapp\UserModel" not found
#0 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#1 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#2 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
ERROR - 2023-07-18 06:15:02 --> mysqli_sql_exception: Table 'pro-manger.users' doesn't exist in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT 1\nFROM `...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\MS\system\Validation\Rules.php(212): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\MS\system\Validation\Validation.php(305): CodeIgniter\Validation\Rules->is_unique('sm12@hotmail.co...', 'email', Array, NULL)
#6 C:\xampp\htdocs\MS\system\Validation\Validation.php(164): CodeIgniter\Validation\Validation->processRules('Email', 'Email', 'sm12@hotmail.co...', Array, Array)
#7 C:\xampp\htdocs\MS\system\Controller.php(181): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(30): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-07-18 06:15:02 --> Class "App\Controllers\Deskapp\UserModel" not found
#0 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#1 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#2 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#4 {main}
ERROR - 2023-07-18 06:17:34 --> mysqli_sql_exception: Table 'pro-manger.users' doesn't exist in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('SELECT 1\nFROM `...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('SELECT 1\nFROM `...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT 1\nFROM `...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT 1\nFROM `...', Array, false)
#4 C:\xampp\htdocs\MS\system\Validation\Rules.php(212): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\MS\system\Validation\Validation.php(305): CodeIgniter\Validation\Rules->is_unique('sm12@hotmail.co...', 'email', Array, NULL)
#6 C:\xampp\htdocs\MS\system\Validation\Validation.php(164): CodeIgniter\Validation\Validation->processRules('Email', 'Email', 'sm12@hotmail.co...', Array, Array)
#7 C:\xampp\htdocs\MS\system\Controller.php(181): CodeIgniter\Validation\Validation->run()
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(30): CodeIgniter\Controller->validate(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-07-18 06:37:59 --> Array to string conversion
#0 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(44): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string...', 'C:\\xampp\\htdocs...', 44)
#1 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#2 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#3 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2023-07-18 06:41:22 --> Array to string conversion
#0 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(44): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string...', 'C:\\xampp\\htdocs...', 44)
#1 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#2 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#3 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2023-07-18 06:42:04 --> Array to string conversion
#0 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(44): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string...', 'C:\\xampp\\htdocs...', 44)
#1 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#2 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#3 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#5 {main}
ERROR - 2023-07-18 06:47:40 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('UPDATE `user...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2472): CodeIgniter\Database\BaseConnection->query('UPDATE `user...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(353): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(887): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\MS\system\Model.php(737): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(663): CodeIgniter\Model->update('10020', Array)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(46): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 06:48:10 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('UPDATE `user...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2472): CodeIgniter\Database\BaseConnection->query('UPDATE `user...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(353): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(887): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\MS\system\Model.php(737): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(663): CodeIgniter\Model->update('10020', Array)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(46): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 06:50:37 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('UPDATE `user...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2472): CodeIgniter\Database\BaseConnection->query('UPDATE `user...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(353): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(887): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\MS\system\Model.php(737): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(663): CodeIgniter\Model->update('10020', Array)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(46): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 06:55:31 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('UPDATE `user...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2472): CodeIgniter\Database\BaseConnection->query('UPDATE `user...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(353): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(887): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\MS\system\Model.php(737): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(663): CodeIgniter\Model->update('10020', Array)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(46): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 06:56:41 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('UPDATE `user...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2472): CodeIgniter\Database\BaseConnection->query('UPDATE `user...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(353): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(887): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\MS\system\Model.php(737): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(663): CodeIgniter\Model->update('10020', Array)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(46): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 06:58:11 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('UPDATE `user...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2472): CodeIgniter\Database\BaseConnection->query('UPDATE `user...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(353): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(887): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\MS\system\Model.php(737): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(663): CodeIgniter\Model->update('10020', Array)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(46): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 07:00:47 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('UPDATE `user...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2472): CodeIgniter\Database\BaseConnection->query('UPDATE `user...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(353): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(887): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\MS\system\Model.php(737): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(663): CodeIgniter\Model->update('10020', Array)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(46): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 07:04:13 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('UPDATE `user...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2472): CodeIgniter\Database\BaseConnection->query('UPDATE `user...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(353): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(887): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\MS\system\Model.php(737): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(663): CodeIgniter\Model->update('10020', Array)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(46): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-07-18 07:04:38 --> Allowed fields must be specified for model: App\Models\UserModel
#0 C:\xampp\htdocs\MS\system\BaseModel.php(1188): CodeIgniter\Database\Exceptions\DataException::forInvalidAllowedFields('App\\Models\\Memb...')
#1 C:\xampp\htdocs\MS\system\BaseModel.php(867): CodeIgniter\BaseModel->doProtectFields(Array)
#2 C:\xampp\htdocs\MS\system\Model.php(737): CodeIgniter\BaseModel->update(Array, Array)
#3 C:\xampp\htdocs\MS\system\BaseModel.php(663): CodeIgniter\Model->update('10020', Array)
#4 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(46): CodeIgniter\BaseModel->save(Array)
#5 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#6 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#7 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2023-07-18 07:15:11 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('UPDATE `user...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2472): CodeIgniter\Database\BaseConnection->query('UPDATE `user...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(353): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(887): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\MS\system\Model.php(737): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(663): CodeIgniter\Model->update('11111', Array)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(46): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 07:23:30 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2023-07-18 07:24:14 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(47): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2023-07-18 07:25:22 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2023-07-18 07:25:33 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2023-07-18 07:26:27 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2023-07-18 07:27:45 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2023-07-18 07:27:58 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('UPDATE `user...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2472): CodeIgniter\Database\BaseConnection->query('UPDATE `user...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(353): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(887): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\MS\system\Model.php(737): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(663): CodeIgniter\Model->update('10020', Array)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 07:28:07 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('UPDATE `user...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2472): CodeIgniter\Database\BaseConnection->query('UPDATE `user...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(353): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(887): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\MS\system\Model.php(737): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(663): CodeIgniter\Model->update('10020', Array)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 07:28:19 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('UPDATE `user...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2472): CodeIgniter\Database\BaseConnection->query('UPDATE `user...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(353): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(887): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\MS\system\Model.php(737): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(663): CodeIgniter\Model->update('10020', Array)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 07:28:49 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('UPDATE `user...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2472): CodeIgniter\Database\BaseConnection->query('UPDATE `user...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(353): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(887): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\MS\system\Model.php(737): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(663): CodeIgniter\Model->update('10020', Array)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 07:29:18 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2023-07-18 07:30:44 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2023-07-18 07:30:58 --> mysqli_sql_exception: Unknown column 'updated_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('UPDATE `user...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('UPDATE `user...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('UPDATE `user...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2472): CodeIgniter\Database\BaseConnection->query('UPDATE `user...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(353): CodeIgniter\Database\BaseBuilder->update()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(887): CodeIgniter\Model->doUpdate(Array, Array)
#6 C:\xampp\htdocs\MS\system\Model.php(737): CodeIgniter\BaseModel->update(Array, Array)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(663): CodeIgniter\Model->update('10020', Array)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 07:32:12 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 07:33:47 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 07:34:01 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-07-18 07:34:22 --> There is no primary key defined when trying to make insert.
#0 C:\xampp\htdocs\MS\system\Model.php(267): CodeIgniter\Database\Exceptions\DataException::forEmptyPrimaryKey('insert')
#1 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#2 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#3 C:\xampp\htdocs\MS\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#4 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\BaseModel->save(Array)
#5 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#6 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#7 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-07-18 07:34:56 --> There is no primary key defined when trying to make insert.
#0 C:\xampp\htdocs\MS\system\Model.php(267): CodeIgniter\Database\Exceptions\DataException::forEmptyPrimaryKey('insert')
#1 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#2 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#3 C:\xampp\htdocs\MS\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#4 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\BaseModel->save(Array)
#5 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#6 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#7 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#9 {main}
ERROR - 2023-07-18 07:35:17 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 07:35:41 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(48): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 07:35:41 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 07:37:25 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(48): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 07:37:25 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 07:38:23 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(40): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 07:38:47 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(48): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 07:38:47 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 07:40:33 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(48): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 07:40:33 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 07:42:44 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(48): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 07:44:01 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(48): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 07:44:33 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(48): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 07:45:55 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 07:46:19 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 07:47:21 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 07:49:11 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2023-07-18 07:53:20 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\Model->insert(Array)
#8 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2023-07-18 08:01:06 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 08:03:09 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 08:05:14 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
ERROR - 2023-07-18 08:06:50 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php:314
Stack trace:
#0 C:\xampp\htdocs\MS\system\Database\MySQLi\Connection.php(314): mysqli->query('INSERT INTO `me...')
#1 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(715): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `me...')
#2 C:\xampp\htdocs\MS\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `me...')
#3 C:\xampp\htdocs\MS\system\Database\BaseBuilder.php(2265): CodeIgniter\Database\BaseConnection->query('INSERT INTO `me...', Array, false)
#4 C:\xampp\htdocs\MS\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\MS\system\BaseModel.php(751): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\MS\system\Model.php(705): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\MS\system\BaseModel.php(667): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\MS\app\Controllers\Deskapp\Register.php(49): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\MS\system\CodeIgniter.php(935): App\Controllers\Deskapp\Register->save()
#10 C:\xampp\htdocs\MS\system\CodeIgniter.php(431): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Deskapp\Register))
#11 C:\xampp\htdocs\MS\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\MS\index.php(44): CodeIgniter\CodeIgniter->run()
#13 {main}
